import { index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const executorState = sqliteTable("executor_state", {
  key: text("key").primaryKey(),
  mode: text("mode").notNull().default("PAPER"),
  armed: integer("armed", { mode: "boolean" }).notNull().default(false),
  riskConfigured: integer("risk_configured", { mode: "boolean" }).notNull().default(false),
  capitalCap: real("capital_cap").notNull().default(50),
  startingBankroll: real("starting_bankroll").notNull().default(50),
  targetMin: integer("target_min").notNull().default(4),
  targetMax: integer("target_max").notNull().default(8),
  maxOrdersPerDay: integer("max_orders_per_day").notNull().default(8),
  baseStake: real("base_stake").notNull().default(1.25),
  maxStake: real("max_stake").notNull().default(2.5),
  maxExposure: real("max_exposure").notNull().default(5),
  maxPositions: integer("max_positions").notNull().default(2),
  dailyStop: real("daily_stop").notNull().default(3),
  weeklyStop: real("weekly_stop").notNull().default(6),
  hardDrawdown: real("hard_drawdown").notNull().default(5),
  lockUntil: integer("lock_until").notNull().default(0),
  lastCycleAt: integer("last_cycle_at"),
  lastScheduledCycleAt: integer("last_scheduled_cycle_at"),
  lastCycleStatus: text("last_cycle_status"),
  lastError: text("last_error"),
  lastGeoBlocked: integer("last_geo_blocked", { mode: "boolean" }),
  lastGeoCountry: text("last_geo_country"),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

export const executionDecisions = sqliteTable("execution_decisions", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  signalKey: text("signal_key").notNull(),
  createdAt: integer("created_at").notNull(),
  sourceTimestamp: integer("source_timestamp").notNull(),
  mode: text("mode").notNull(),
  status: text("status").notNull(),
  category: text("category").notNull(),
  title: text("title").notNull(),
  outcome: text("outcome").notNull(),
  marketSlug: text("market_slug"),
  eventSlug: text("event_slug"),
  tokenId: text("token_id"),
  conditionId: text("condition_id"),
  score: integer("score").notNull(),
  wallets: integer("wallets").notNull(),
  operations: integer("operations").notNull(),
  buyPressure: real("buy_pressure").notNull(),
  flowAmount: real("flow_amount").notNull(),
  predictedProbability: real("predicted_probability").notNull(),
  marketProbability: real("market_probability").notNull(),
  edgePoints: real("edge_points").notNull(),
  requestedPrice: real("requested_price").notNull(),
  maximumPrice: real("maximum_price").notNull(),
  fillPrice: real("fill_price"),
  stake: real("stake").notNull().default(0),
  shares: real("shares").notNull().default(0),
  spread: real("spread"),
  bookDepth: real("book_depth"),
  orderId: text("order_id"),
  transactionHash: text("transaction_hash"),
  rejectReason: text("reject_reason"),
  result: integer("result"),
  pnl: real("pnl"),
  resolvedAt: integer("resolved_at"),
}, table => [
  uniqueIndex("execution_decisions_signal_unique").on(table.signalKey),
  index("execution_decisions_status_time_idx").on(table.status, table.createdAt),
  index("execution_decisions_market_idx").on(table.marketSlug, table.createdAt),
]);

export const executionStrategy = sqliteTable("execution_strategy", {
  key: text("key").primaryKey(),
  makerEntryEnabled: integer("maker_entry_enabled", { mode: "boolean" }).notNull().default(true),
  makerImprovementTicks: integer("maker_improvement_ticks").notNull().default(1),
  makerTimeoutSeconds: integer("maker_timeout_seconds").notNull().default(90),
  takerFallbackEnabled: integer("taker_fallback_enabled", { mode: "boolean" }).notNull().default(true),
  takeProfitEnabled: integer("take_profit_enabled", { mode: "boolean" }).notNull().default(true),
  takeProfitPercent: real("take_profit_percent").notNull().default(8),
  minimumProfitTicks: integer("minimum_profit_ticks").notNull().default(2),
  updatedAt: integer("updated_at").notNull(),
});

export const executionOrders = sqliteTable("execution_orders", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  decisionId: integer("decision_id").notNull().references(() => executionDecisions.id),
  orderId: text("order_id").notNull(),
  purpose: text("purpose").notNull(),
  side: text("side").notNull(),
  orderType: text("order_type").notNull(),
  postOnly: integer("post_only", { mode: "boolean" }).notNull().default(false),
  status: text("status").notNull(),
  requestedPrice: real("requested_price").notNull(),
  requestedSize: real("requested_size").notNull(),
  filledSize: real("filled_size").notNull().default(0),
  averageFillPrice: real("average_fill_price"),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
  expiresAt: integer("expires_at"),
  canceledAt: integer("canceled_at"),
  failureReason: text("failure_reason"),
  transactionHash: text("transaction_hash"),
}, table => [
  uniqueIndex("execution_orders_order_unique").on(table.orderId),
  index("execution_orders_decision_idx").on(table.decisionId, table.createdAt),
  index("execution_orders_status_idx").on(table.status, table.updatedAt),
]);

export const executionNetwork = sqliteTable("execution_network", {
  key: text("key").primaryKey(),
  proxyUrl: text("proxy_url").notNull(),
  executionRegion: text("execution_region").notNull(),
  installedAt: integer("installed_at").notNull(),
  lastVerifiedAt: integer("last_verified_at").notNull(),
});

export const cycleLog = sqliteTable("cycle_log", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  startedAt: integer("started_at").notNull(),
  completedAt: integer("completed_at"),
  trigger: text("trigger").notNull(),
  status: text("status").notNull(),
  candidates: integer("candidates").notNull().default(0),
  accepted: integer("accepted").notNull().default(0),
  rejected: integer("rejected").notNull().default(0),
  message: text("message"),
}, table => [index("cycle_log_time_idx").on(table.startedAt)]);

export const credentialVault = sqliteTable("credential_vault", {
  key: text("key").primaryKey(),
  ciphertext: text("ciphertext").notNull(),
  iv: text("iv").notNull(),
  version: integer("version").notNull(),
  actorHash: text("actor_hash").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

export const tradingAccountStatus = sqliteTable("trading_account_status", {
  key: text("key").primaryKey(),
  accountVerifiedAt: integer("account_verified_at"),
  approvalsPreparedAt: integer("approvals_prepared_at"),
  verifiedWallet: text("verified_wallet"),
  verifiedSigner: text("verified_signer"),
  walletType: text("wallet_type"),
  openOrdersSeen: integer("open_orders_seen"),
  lastAuthError: text("last_auth_error"),
  updatedAt: integer("updated_at").notNull(),
});
